import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import { Link, animateScroll as scroll, Events, scrollSpy } from "react-scroll";
import Menu from "../components/Menu";
import Section from "../components/Section";
import { projects } from "../data/projects";

export default function Home() {
  const projectTypes = ["work", "playground", "bookshelf"];

  useEffect(() => {
    Events.scrollEvent.register("begin", function () {
      console.log("begin", arguments);
    });

    Events.scrollEvent.register("end", function () {
      console.log("end", arguments);
    });

    scrollSpy.update();

    return () => {
      Events.scrollEvent.remove("begin");
      Events.scrollEvent.remove("end");
    };
  }, []);

  return (
    <>
      <Head>
        <title>Soy Kim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex font-aeonik">
        <div className="z-50">
          <Menu projects={projects} />
        </div>

        <div className="flex-grow ml-[300px] phone:ml-0 w-full">
          <div id="soy" className="p-8 text-xl pt-24  text-black w-full">
            <div className="max-w-[550px] leading-snug">
              <div>Hi, I'm Soyeon.</div>
              <div>
                I'm a motion designer specializing in branding from Seoul, based
                in NYC. I'm currently a designer at Google Creative Lab.
              </div>
              <div className="mt-8">
                Read more about me{" "}
                <a className="underline" href="/about">
                  here
                </a>
                .
              </div>
            </div>
            <div className="bg-gray-100 mt-2 w-full h-96"></div>
          </div>
          {projects.slice(1).map((project, index) => (
            <Section key={index} project={project}></Section>
          ))}
          <div className="py-96 p-2 border-0 border-t-[0.5px] border-black">
            Thanks for making it to the end of the page! Leave a note for me...
          </div>
        </div>
      </main>
    </>
  );
}
